#include "stdafx.h"
#include "ConnectedUser.h"
#include "GameCtrlParams.h"

bool CConnectedUser::db_UpdateUserAccountInfo(CMySqlSessionPool mySqlSessionPool)
{
	CMySqlSession * mySqlSession = mySqlSessionPool.GetFreeSession();
	
	sprintf(mySqlSession->mCommand, "update %s set NICKNAME = '%s', PASSWORD = '%s', BIND_ACCOUNT_TYPE = '%s', BIND_ACCOUNT = '%s', CELLPHONE_NO = '%s', INTEGRAL_POINTS = %d, LEVEL = %d, DIAMONDS = %d, COINS = %d, WIN_TIMES = %d, BATTLE_TIMES = %d, WIN_RATE = %f, SHOT_DOWN_PLANES = %d, SHOT_DOWN_JUNIOR_PLANES = %d, SHOT_DOWN_MIDDLE_PLANES = %d, SHOT_DOWN_SENIOR_PLANES = %d where USER_ID = %d", 
		USER_TABLE_NAME, 
		mUserAccountInfo.NICKNAME, 
		mUserAccountInfo.PASSWORD,
		mUserAccountInfo.BIND_ACCOUNT_TYPE, 
		mUserAccountInfo.BIND_ACCOUNT, 
		mUserAccountInfo.CELLPHONE_NO, 
		mUserAccountInfo.INTEGRAL_POINTS, 
		mUserAccountInfo.LEVEL, 
		mUserAccountInfo.DIAMONDS, 
		mUserAccountInfo.COINS, 
		mUserAccountInfo.WIN_TIMES, 
		mUserAccountInfo.BATTLE_TIMES, 
		mUserAccountInfo.WIN_RATE, 
		mUserAccountInfo.SHOT_DOWN_PLANES, 
		mUserAccountInfo.SHOT_DOWN_JUNIOR_PLANES, 
		mUserAccountInfo.SHOT_DOWN_MIDDLE_PLANES, 
		mUserAccountInfo.SHOT_DOWN_SENIOR_PLANES,
		mUserAccountInfo.USER_ID);

	if(!mySqlSession->OPERATE_DATA())
		return FALSE;

	sprintf(mySqlSession->mCommand, "update %s set LEVEL = %d, JUNIOR_PLANE_CARD_NUM = %d, MIDDLE_PLANE_CARD_NUM = %d, SENIOR_PLANE_CARD_NUM = %d, JUNIOR_STEALTH_PLANE_CARD_NUM = %d, MIDDLE_STEALTH_PLANE_CARD_NUM = %d, SENIOR_STEALTH_PLANE_CARD_NUM = %d, SENIOR_ANTI_STEALTH_RADAR_CARD_NUM = %d, MIDDLE_ANTI_STEALTH_RADAR_CARD_NUM = %d, JUNIOR_ANTI_STEALTH_RADAR_CARD_NUM = %d, SENIOR_MISSILE_CARD_NUM = %d, MIDDLE_MISSILE_CARD_NUM = %d, JUNIOR_MISSILE_CARD_NUM = %d, SENIOR_RADAR_CARD_NUM = %d, MIDDLE_RADAR_CARD_NUM = %d, JUNIOR_RADAR_CARD_NUM = %d, SENIOR_CANNONBALL_CARD_NUM = %d, MIDDLE_CANNONBALL_CARD_NUM = %d, JUNIOR_CANNONBALL_CARD_NUM = %d, JUNIOR_PLANE_LEVEL = %d, MIDDLE_PLANE_LEVEL = %d, SENIOR_PLANE_LEVEL = %d, JUNIOR_STEALTH_PLANE_LEVEL = %d, MIDDLE_STEALTH_PLANE_LEVEL = %d, SENIOR_STEALTH_PLANE_LEVEL = %d, SENIOR_ANTI_STEALTH_RADAR_LEVEL = %d, MIDDLE_ANTI_STEALTH_RADAR_LEVEL = %d, JUNIOR_ANTI_STEALTH_RADAR_LEVEL = %d, SENIOR_MISSILE_LEVEL = %d, MIDDLE_MISSILE_LEVEL = %d, JUNIOR_MISSILE_LEVEL = %d, SENIOR_RADAR_LEVEL = %d, MIDDLE_RADAR_LEVEL = %d, JUNIOR_RADAR_LEVEL = %d, SENIOR_CANNONBALL_LEVEL = %d, MIDDLE_CANNONBALL_LEVEL = %d, JUNIOR_CANNONBALL_LEVEL = %d where USER_ID = %d", 
		EQUIPMENT_TABLE_NAME,
		mUserEquipmentInfo.LEVEL,
		mUserEquipmentInfo.JUNIOR_PLANE_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_PLANE_CARD_NUM,
		mUserEquipmentInfo.SENIOR_PLANE_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_STEALTH_PLANE_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_STEALTH_PLANE_CARD_NUM,
		mUserEquipmentInfo.SENIOR_STEALTH_PLANE_CARD_NUM,
		mUserEquipmentInfo.SENIOR_ANTI_STEALTH_RADAR_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_ANTI_STEALTH_RADAR_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_ANTI_STEALTH_RADAR_CARD_NUM,
		mUserEquipmentInfo.SENIOR_MISSILE_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_MISSILE_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_MISSILE_CARD_NUM,
		mUserEquipmentInfo.SENIOR_RADAR_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_RADAR_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_RADAR_CARD_NUM,
		mUserEquipmentInfo.SENIOR_CANNONBALL_CARD_NUM,
		mUserEquipmentInfo.MIDDLE_CANNONBALL_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_CANNONBALL_CARD_NUM,
		mUserEquipmentInfo.JUNIOR_PLANE_LEVEL,
		mUserEquipmentInfo.MIDDLE_PLANE_LEVEL,
		mUserEquipmentInfo.SENIOR_PLANE_LEVEL,
		mUserEquipmentInfo.JUNIOR_STEALTH_PLANE_LEVEL,
		mUserEquipmentInfo.MIDDLE_STEALTH_PLANE_LEVEL,
		mUserEquipmentInfo.SENIOR_STEALTH_PLANE_LEVEL,
		mUserEquipmentInfo.SENIOR_ANTI_STEALTH_RADAR_LEVEL,
		mUserEquipmentInfo.MIDDLE_ANTI_STEALTH_RADAR_LEVEL,
		mUserEquipmentInfo.JUNIOR_ANTI_STEALTH_RADAR_LEVEL,
		mUserEquipmentInfo.SENIOR_MISSILE_LEVEL,
		mUserEquipmentInfo.MIDDLE_MISSILE_LEVEL,
		mUserEquipmentInfo.JUNIOR_MISSILE_LEVEL,
		mUserEquipmentInfo.SENIOR_RADAR_LEVEL,
		mUserEquipmentInfo.MIDDLE_RADAR_LEVEL,
		mUserEquipmentInfo.JUNIOR_RADAR_LEVEL,
		mUserEquipmentInfo.SENIOR_CANNONBALL_LEVEL,
		mUserEquipmentInfo.MIDDLE_CANNONBALL_LEVEL,
		mUserEquipmentInfo.JUNIOR_CANNONBALL_LEVEL,
		mUserAccountInfo.USER_ID);

	if(!mySqlSession->OPERATE_DATA())
		return FALSE;

	sprintf(mySqlSession->mCommand, "update %s set STAR_NUM = %d, WIN_REWARDS_1_NUM = %d, WIN_REWARDS_2_NUM = %d, WIN_REWARDS_3_NUM = %d, WIN_REWARDS_4_NUM = %d, WIN_REWARDS_5_NUM = %d, STAR_REWARDS_NUM = %d, FREE_REWARDS_NUM = %d, WIN_REWARDS_1_UNLOCK_TIME = %I64d, WIN_REWARDS_2_UNLOCK_TIME = %I64d,  WIN_REWARDS_3_UNLOCK_TIME = %I64d, WIN_REWARDS_4_UNLOCK_TIME = %I64d, WIN_REWARDS_5_UNLOCK_TIME = %I64d, LAST_STAR_REWARDS_ACQUIRE_TIME = %I64d, LAST_FREE_REWARDS_ACQUIRE_TIME = %I64d  where USER_ID = %d", 
		CHEST_TABLE_NAME, 
		mUserChestInfo.STAR_NUM,
		mUserChestInfo.WIN_REWARDS_1_NUM,
		mUserChestInfo.WIN_REWARDS_2_NUM,
		mUserChestInfo.WIN_REWARDS_3_NUM,
		mUserChestInfo.WIN_REWARDS_4_NUM,
		mUserChestInfo.WIN_REWARDS_5_NUM,
		mUserChestInfo.STAR_REWARDS_NUM,
		mUserChestInfo.FREE_REWARDS_NUM,
		mUserChestInfo.WIN_REWARDS_1_UNLOCK_TIME,
		mUserChestInfo.WIN_REWARDS_2_UNLOCK_TIME,
		mUserChestInfo.WIN_REWARDS_3_UNLOCK_TIME,
		mUserChestInfo.WIN_REWARDS_4_UNLOCK_TIME,
		mUserChestInfo.WIN_REWARDS_5_UNLOCK_TIME,
		mUserChestInfo.LAST_STAR_REWARDS_ACQUIRE_TIME,
		mUserChestInfo.LAST_FREE_REWARDS_ACQUIRE_TIME,
		mUserChestInfo.USER_ID);

	if(!mySqlSession->OPERATE_DATA())
		return FALSE;

	mySqlSession->FreeSession();

	return TRUE;
}

